title: Developer Kyeongwon Jang
subtitle: I'm still growing up
description: >- # this means to ignore newlines until "baseurl:"
  Kyeongwon Jang - Dev

url: "https://indiaink10.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Blog
      url: /blog
    - text: About Me
      url: /about/
    - text: Contact Me
      url : /contact/
    

# Edit these details 

author_logo: profile.png
author: Kyeongwon Jang
author_bio: Hi, My Name is Kyeongwon Jang. I love to Code and Design. devlopr-jekyll is a theme built for developers.  
author_email: "indiaink10@gmail.com"
author_location: Korea
author_website_url: "https://indiaink10.github.io" # http://johndoe.com

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: knu.png # must change
                college_name: KNU
                college_url: https://www.kangwon.ac.kr/www/index.do
                college_degree: Computer Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
                project_thumbnail: areaofshapecalculator.png
                project_title: Area of ​​Shape Calculator
                project_description: a Program to easily calculate area of shape ( Visual Basic )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: movieinformation.png
                project_title: Movie Information
                project_description: a Program to easily get movie information ( Visual Basic )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: palindrome.png
                project_title: Palindrome
                project_description: a Program to determine whether it is a palindrome ( C )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: maze.png
                project_title: Maze
                project_description: a Program to escape the maze ( C )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: polynomialcalculation.png
                project_title: Polynomial calculation
                project_description: a Program for calculating the sum of input polynomials ( C )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: phonebook.png
                project_title: Phonebook
                project_description: Implement the currently used phone book app as a program ( C )
                project_url: https://programmingebooks.com
                visibility: true         
                project_thumbnail: videorental.png
                project_title: VideoRental
                project_description: Implement a video rental program with a database ( C )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: samcheokcultureandtourism.png
                project_title: Samcheok Culture and Tourism
                project_description: Samcheok Culture & Tourism Web Document using html tags ( HTML )
                project_url: https://programmingebooks.com
                visibility: true
                project_thumbnail: similargoogle.png
                project_title: Similar Google
                project_description: Web documents made similar to Google search site using css and webforms ( HTML )
                project_url: https://programmingebooks.com
                visibility: true
                

# social links
twitter_username: indiaink10
github_username:  indiaink10
facebook_username: indiaink10
linkedin_username: indiaink10
behance_username: indiaink10
instagram_username: indiaink10
medium_username: indiaink10
telegram_username: indiaink10
dribbble_username: indiaink10
flickr_username: indiaink10

#for comments using disqus
disqus_shortname: indiaink10

# wakatime username (coding activity)
wakatime_username: indiaink10

# formspree (contact form)
formspree_email: indiaink10@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
